id = "noir"
name = "Noir"
description = "Noir support."
version = "0.0.2"
schema_version = 1
authors = ["Ayush Shukla <ayush@shuklaayu.sh>"]
repository = "https://github.com/shuklaayush/zed-noir"

[language_servers.nargo]
name = "Noir Language Server"
languages = ["Noir"]

[grammars.noir]
repository = "https://github.com/hhamud/tree-sitter-noir"
rev = "2256df2be2d45b7c92d11927734d0547fd08af5f"
