id = "noir"
name = "Noir"
description = "Noir support."
version = "0.0.1"
schema_version = 1
authors = ["Ayush Shukla <ayush@shuklaayu.sh>"]
repository = "https://github.com/shuklaayush/zed-noir"

[language_servers.nargo]
name = "Noir Language Server"
languages = ["Noir"]

[grammars.noir]
repository = "file:///home/franco/Documents/agents/noir-zed-lab/tree-sitter-noir"
rev = "20b83e0cef546e454aed44cec5c403235fb848aa"
